//! Scaffold new plugin folders with manifest, entry script, and README.

use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::{AppError, AppResult};
use crate::plugins::analyze::{analyze_main_js, validate_manifest_fields};
use crate::plugins::editor::write_plugin_files;
use crate::plugins::manifest::PluginManifest;

pub fn is_valid_plugin_id(id: &str) -> bool {
    let mut parts = id.split('.');
    let Some(first) = parts.next() else {
        return false;
    };
    if first.is_empty() || !first.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit()) {
        return false;
    }
    for part in parts {
        if part.is_empty() {
            return false;
        }
        let Some(first_char) = part.chars().next() else {
            return false;
        };
        if !first_char.is_ascii_lowercase() && !first_char.is_ascii_digit() {
            return false;
        }
        if !part
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
        {
            return false;
        }
    }
    id.contains('.')
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreatePluginSpec {
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    pub author: Option<String>,
    pub action_id: String,
    pub action_label: String,
    pub main_js: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CreatePluginResult {
    pub id: String,
    pub dir: String,
}

pub fn create_plugin(plugins_dir: &Path, spec: CreatePluginSpec) -> AppResult<CreatePluginResult> {
    let id = spec.id.trim().to_string();
    let name = spec.name.trim().to_string();
    let action_id = spec.action_id.trim().to_string();
    let action_label = spec.action_label.trim().to_string();

    if id.is_empty() {
        return Err(AppError::msg("Plugin id is required"));
    }
    if name.is_empty() {
        return Err(AppError::msg("Plugin name is required"));
    }
    if action_id.is_empty() || action_label.is_empty() {
        return Err(AppError::msg("Action id and label are required"));
    }

    if !is_valid_plugin_id(&id) {
        return Err(AppError::msg(
            "Plugin id must be reverse-DNS, e.g. com.yourname.my-plugin",
        ));
    }

    let plugin_dir = plugins_dir.join(&id);
    if plugin_dir.exists() {
        return Err(AppError::msg(format!(
            "A plugin with id '{id}' already exists"
        )));
    }

    std::fs::create_dir_all(&plugin_dir)?;

    let main_js = spec
        .main_js
        .filter(|s| !s.trim().is_empty())
        .unwrap_or_else(|| render_main_js(&name, &action_id));

    let mut analysis = analyze_main_js(&main_js);
    for issue in validate_manifest_fields(&id, &name, &action_id, &action_label) {
        if issue.severity == "error" {
            analysis.issues.push(issue);
        } else {
            analysis.warnings.push(issue);
        }
    }
    if analysis.issues.iter().any(|i| i.severity == "error") {
        let _ = std::fs::remove_dir_all(&plugin_dir);
        let msg = analysis
            .issues
            .iter()
            .map(|i| i.message.as_str())
            .collect::<Vec<_>>()
            .join("; ");
        return Err(AppError::msg(format!("PLUGIN_INVALID_MANIFEST: {msg}")));
    }

    write_plugin_files(
        &plugin_dir,
        &id,
        &name,
        spec.description.as_deref(),
        spec.author.as_deref(),
        &action_id,
        &action_label,
        &main_js,
        &analysis.permissions,
        None,
    )?;

    Ok(CreatePluginResult {
        id,
        dir: plugin_dir.display().to_string(),
    })
}

fn render_main_js(name: &str, _action_id: &str) -> String {
    format!(
        r#"/**
 * {name}
 *
 * Starter plugin generated by Lumora. Edit runAction() below.
 */

export async function runAction(actionId, context) {{
  lumora.log("info", `${{actionId}}: ${{context.assetIds.length}} asset(s) selected`);
  context.reportProgress(0, context.assetIds.length);

  // Example: load asset metadata when read:assets is granted in the manifest.
  // const assets = await lumora.getAssets(context.assetIds);
  // lumora.log("info", `First asset path: ${{assets[0]?.path ?? "n/a"}}`);

  for (let i = 0; i < context.assetIds.length; i++) {{
    lumora.log("info", `  [${{i + 1}}] ${{context.assetIds[i]}}`);
    context.reportProgress(i + 1, context.assetIds.length);
  }}

  return {{
    ok: true,
    message: `Processed ${{context.assetIds.length}} asset(s)`,
  }};
}}
"#
    )
}

pub fn render_readme(manifest: &PluginManifest, action_id: &str, action_label: &str) -> String {
    let perms = if manifest.permissions.is_empty() {
        "None".to_string()
    } else {
        manifest.permissions.join(", ")
    };

    format!(
        r#"# {name}

{description}

## Permissions

{perms}

## Usage

1. Select one or more photos in your library.
2. Click **Plugins** in the selection bar.
3. Choose **{action_label}**.

## Files

- `lumora.plugin.json` — manifest (id, permissions, actions)
- `main.js` — exports `runAction(actionId, context)`

## Editing

Update `runAction()` in `main.js`. The host calls it when the user runs action `{action_id}`.

```js
export async function runAction(actionId, context) {{
  // context.assetIds — selected photo ids
  // context.mode — "preview" or "apply"
  // context.reportProgress(current, total) — updates the progress dialog
  // lumora.log(level, message) — writes to plugin run history
  return {{ ok: true, message: "Done" }};
}}
```

Author: {author}
"#,
        name = manifest.name,
        description = manifest.description,
        perms = perms,
        action_label = action_label,
        action_id = action_id,
        author = manifest.author,
    )
}
